# Generated by Django 5.2.5 on 2025-09-29 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='academicyear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='examdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('YEAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='semdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YEAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.academicyear')),
                ('SEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.semester')),
            ],
        ),
        migrations.CreateModel(
            name='staffdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('design', models.CharField(default='Staff', max_length=1000)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=600)),
                ('phoneno', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='staffs/')),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.staffdata')),
            ],
        ),
        migrations.CreateModel(
            name='studentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('rollno', models.CharField(max_length=500)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=600)),
                ('phoneno', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='students/')),
                ('SEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.semester')),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('YEAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='examresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('EXAM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.examdata')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='assignmentdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ASSIGN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.assignment')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.studentdata')),
            ],
        ),
        migrations.CreateModel(
            name='subjectdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=1000)),
                ('syllabus', models.TextField(blank=True, null=True)),
                ('SEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.semester')),
                ('STAFF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='a_app.staffdata')),
            ],
        ),
        migrations.CreateModel(
            name='studymaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='studymaterials/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.staffdata')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.subjectdata')),
            ],
        ),
        migrations.CreateModel(
            name='internal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.IntegerField()),
                ('test2', models.IntegerField()),
                ('total', models.IntegerField()),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.studentdata')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.subjectdata')),
            ],
        ),
        migrations.AddField(
            model_name='examdata',
            name='SUBJECT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.subjectdata'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='SUBJECT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.subjectdata'),
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('SEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.semdata')),
                ('SUBJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.subjectdata')),
            ],
        ),
    ]
