# Generated by Django 5.2.5 on 2025-10-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='internal',
        ),
    ]
