# Generated by Django 5.2.5 on 2025-10-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0002_delete_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdata',
            name='SEMDATA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='a_app.semdata'),
            preserve_default=False,
        ),
    ]
