# Generated by Django 5.2.5 on 2025-10-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_app', '0003_examdata_semdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=False)),
                ('SEM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.semester')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.staffdata')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.studentdata')),
                ('YEAR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_app.academicyear')),
            ],
        ),
    ]
